import {
  Injectable,
  UnauthorizedException,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateApiKeyDto } from './dto/create-api-key.dto';
import * as bcrypt from 'bcrypt';
import * as crypto from 'crypto';

@Injectable()
export class ApiKeysService {
  private readonly logger = new Logger(ApiKeysService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generates a new API key. Returns the raw key ONCE — it cannot be retrieved again.
   * The raw key is bcrypt-hashed before storage.
   */
  async generate(adminId: string, dto: CreateApiKeyDto): Promise<{ id: string; name: string; prefix: string; rawKey: string; createdAt: Date }> {
    const rawKey = `vem_${crypto.randomBytes(24).toString('hex')}`;
    const prefix = rawKey.substring(0, 8);
    const keyHash = await bcrypt.hash(rawKey, 10);

    const apiKey = await this.prisma.apiKey.create({
      data: {
        name: dto.name,
        keyHash,
        prefix,
        createdById: adminId,
      },
    });

    this.logger.log(`API key "${dto.name}" generated by admin ${adminId} (prefix: ${prefix})`);

    return {
      id: apiKey.id,
      name: apiKey.name,
      prefix: apiKey.prefix,
      rawKey,
      createdAt: apiKey.createdAt,
    };
  }

  /**
   * Validates an incoming raw API key against all active keys.
   * Updates lastUsedAt on success.
   * Throws UnauthorizedException on failure — never leaks reason.
   */
  async validateKey(rawKey: string): Promise<void> {
    if (!rawKey) {
      throw new UnauthorizedException('API key required');
    }

    // Fetch all active keys and compare — bcrypt compare is the source of truth
    const activeKeys = await this.prisma.apiKey.findMany({
      where: { isActive: true },
      select: { id: true, keyHash: true },
    });

    let matchedId: string | null = null;

    for (const key of activeKeys) {
      const isMatch = await bcrypt.compare(rawKey, key.keyHash);
      if (isMatch) {
        matchedId = key.id;
        break;
      }
    }

    if (!matchedId) {
      this.logger.warn(`Invalid API key attempt (prefix: ${rawKey.substring(0, 8)}...)`);
      throw new UnauthorizedException('Invalid or revoked API key');
    }

    // Update lastUsedAt — fire and forget, do not block the request
    this.prisma.apiKey
      .update({ where: { id: matchedId }, data: { lastUsedAt: new Date() } })
      .catch((err: Error) => this.logger.error('Failed to update lastUsedAt', err.stack));
  }

  /**
   * Lists all API keys (metadata only — no hashes or raw keys).
   */
  async findAll(): Promise<{ id: string; name: string; prefix: string; isActive: boolean; lastUsedAt: Date | null; createdAt: Date; revokedAt: Date | null }[]> {
    return this.prisma.apiKey.findMany({
      select: {
        id: true,
        name: true,
        prefix: true,
        isActive: true,
        lastUsedAt: true,
        createdAt: true,
        revokedAt: true,
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Revokes an API key. Idempotent — revoking an already-revoked key is a no-op.
   */
  async revoke(id: string, adminId: string): Promise<void> {
    const key = await this.prisma.apiKey.findUnique({ where: { id } });

    if (!key) {
      throw new NotFoundException(`API key ${id} not found`);
    }

    if (!key.isActive) {
      return; // Already revoked — idempotent
    }

    await this.prisma.apiKey.update({
      where: { id },
      data: { isActive: false, revokedAt: new Date() },
    });

    this.logger.log(`API key "${key.name}" (${key.prefix}...) revoked by admin ${adminId}`);
  }
}
