import { ApiProperty } from "@nestjs/swagger";
import { UserStatus } from "@prisma/client";
import { IsEnum, IsString, IsNotEmpty } from "class-validator";

export class NetworkRecruitResponseDto {
  @ApiProperty({ description: "Recruit user identifier", example: "user-uuid" })
  id: string;

  @ApiProperty({ description: "Recruit full name", example: "Jane Smith" })
  fullName: string;

  @ApiProperty({
    description: "Recruit email address",
    example: "jane@example.com",
  })
  email: string;

  @ApiProperty({
    enum: UserStatus,
    description: "Recruit account status",
    example: UserStatus.ACTIVE,
  })
  status: UserStatus;

  @ApiProperty({
    description: "Date when recruit joined",
    example: "2026-04-15T10:00:00.000Z",
  })
  createdAt: Date;

  @ApiProperty({
    description: "Total earnings generated by the recruit in kobo",
    example: 75000,
  })
  totalEarnings: number;

  @ApiProperty({
    description: "Number of businesses referred by the recruit",
    example: 10,
  })
  referralCount: number;

  @ApiProperty({
    description: "Number of active businesses referred by the recruit",
    example: 8,
  })
  businessCount: number;

  @ApiProperty({
    description: "10% of the recruit's total business volume in kobo",
    example: 7500,
  })
  managerShare: number;
}

export class PaginatedNetworkRecruitResponseDto {
  @ApiProperty({
    type: [NetworkRecruitResponseDto],
    description: "Array of recruit objects",
  })
  data: NetworkRecruitResponseDto[];

  @ApiProperty({
    description: "Pagination metadata",
    example: { total: 20, page: 1, limit: 10, totalPages: 2 },
  })
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

class MilestoneInfo {
  @ApiProperty({ description: "Current count achieved", example: 8 })
  current: number;

  @ApiProperty({ description: "Target count needed", example: 10 })
  target: number;

  @ApiProperty({
    description: "Whether the milestone has been reached",
    example: false,
  })
  isReached: boolean;
}

class MilestonesDto {
  @ApiProperty({
    type: MilestoneInfo,
    description: "Agent recruitment milestone progress",
  })
  agents: MilestoneInfo;

  @ApiProperty({
    type: MilestoneInfo,
    description: "Business referral milestone progress",
  })
  businesses: MilestoneInfo;
}

export class NetworkStatsResponseDto {
  @ApiProperty({ description: "Number of active direct recruits", example: 15 })
  activeAgentsCount: number;

  @ApiProperty({
    description: "Total number of businesses in the network",
    example: 45,
  })
  totalNetworkBusinesses: number;

  @ApiProperty({
    type: MilestonesDto,
    description: "Milestone progress towards manager mode",
  })
  milestones: MilestonesDto;

  @ApiProperty({
    description: "Date when manager qualification expires, if applicable",
    required: false,
    nullable: true,
  })
  managerQualificationExpiry: Date | null;

  @ApiProperty({
    description: "Whether manager mode (10% override earnings) is active",
    example: true,
  })
  isManagerMode: boolean;

  @ApiProperty({
    description: "Whether agent milestone bonus has been claimed",
    example: false,
  })
  hasClaimedAgentBonus: boolean;

  @ApiProperty({
    description: "Whether business milestone bonus has been claimed",
    example: true,
  })
  hasClaimedBusinessBonus: boolean;
}

export enum BonusType {
  AGENT = "AGENT",
  BUSINESS = "BUSINESS",
}

export class ClaimBonusDto {
  @ApiProperty({ enum: BonusType, description: "Type of bonus to claim" })
  @IsEnum(BonusType)
  @IsNotEmpty()
  type: BonusType;
}
