import { 
  MarketMappingStats, 
  GeographicHierarchyNode, 
  ClusterDetail, 
  MappedBusiness,
  ExpansionStageInfo
} from '@/types/market-mapping';

export const mockMarketStats: MarketMappingStats = {
  commercialAreas: 24,
  commercialClusters: 68,
  businessesMapped: 1420,
  verifiedBusinesses: 1180,
  vemtapCustomers: 412,
  prospects: 1008,
  anchorBusinesses: 56,
  assignedAffiliates: 38,
  averagePenetration: 29.0,
  todayVisits: 42,
  todayNewCustomers: 6,
};

export const mockExpansionStages: ExpansionStageInfo[] = [
  { stage: 1, name: 'Cluster Created', description: 'Commercial cluster boundaries established by Admin.', isCompleted: true, completedAt: '2026-06-01' },
  { stage: 2, name: 'Businesses Mapped', description: 'All potential businesses identified within cluster bounds.', isCompleted: true, completedAt: '2026-06-05' },
  { stage: 3, name: 'Businesses Verified', description: 'Field affiliate verified owner contact and foot traffic.', isCompleted: true, completedAt: '2026-06-12' },
  { stage: 4, name: 'First Affiliate Assigned', description: 'Lead affiliate deployed to manage cluster territory.', isCompleted: true, completedAt: '2026-06-15' },
  { stage: 5, name: 'First Anchor Signed', description: 'High-traffic anchor business onboarded onto Vemtap.', isCompleted: true, completedAt: '2026-06-25' },
  { stage: 6, name: 'First 10 Customers', description: 'Initial core group of merchant customers activated.', isCompleted: true, completedAt: '2026-07-02' },
  { stage: 7, name: 'Customer Partnership Network Active', description: 'Cross-promotion ecosystem operating between merchants.', isCompleted: false },
  { stage: 8, name: '25% Market Penetration', description: 'Quarter of total cluster merchant capacity onboarded.', isCompleted: false },
  { stage: 9, name: '50% Market Penetration', description: 'Half of cluster merchants active on Vemtap network.', isCompleted: false },
  { stage: 10, name: 'Cluster Dominated', description: 'Dominant market share achieved in commercial area.', isCompleted: false },
];

export const mockHierarchy: GeographicHierarchyNode[] = [
  { id: 'ng', name: 'Nigeria', type: 'COUNTRY', childrenCount: 36, totalBusinesses: 1420, totalCustomers: 412, totalProspects: 1008, totalAnchors: 56, penetrationPercentage: 29, latitude: 9.0820, longitude: 8.6753 },
  { id: 'fct', name: 'FCT', type: 'STATE', parentId: 'ng', childrenCount: 6, totalBusinesses: 850, totalCustomers: 260, totalProspects: 590, totalAnchors: 34, penetrationPercentage: 30.5, latitude: 8.8932, longitude: 7.1812 },
  { id: 'abuja', name: 'Abuja', type: 'CITY', parentId: 'fct', childrenCount: 8, totalBusinesses: 620, totalCustomers: 210, totalProspects: 410, totalAnchors: 26, penetrationPercentage: 33.8, latitude: 9.0765, longitude: 7.3986 },
  { id: 'wuse', name: 'Wuse', type: 'AREA', parentId: 'abuja', childrenCount: 5, totalBusinesses: 240, totalCustomers: 95, totalProspects: 145, totalAnchors: 12, penetrationPercentage: 39.5, latitude: 9.0775, longitude: 7.4720 },
  { id: 'banex', name: 'Banex Plaza', type: 'CLUSTER', parentId: 'wuse', totalBusinesses: 120, totalCustomers: 48, totalProspects: 72, totalAnchors: 6, penetrationPercentage: 40, clusterStage: 6, latitude: 9.0765, longitude: 7.4898 },
  { id: 'wuse-mkt', name: 'Wuse Main Market', type: 'CLUSTER', parentId: 'wuse', totalBusinesses: 85, totalCustomers: 32, totalProspects: 53, totalAnchors: 4, penetrationPercentage: 37.6, clusterStage: 5, latitude: 9.0780, longitude: 7.4700 },
  { id: 'garki', name: 'Garki', type: 'AREA', parentId: 'abuja', childrenCount: 4, totalBusinesses: 180, totalCustomers: 50, totalProspects: 130, totalAnchors: 8, penetrationPercentage: 27.7, latitude: 9.0289, longitude: 7.4877 },
  { id: 'garki-mkt', name: 'Garki Model Market', type: 'CLUSTER', parentId: 'garki', totalBusinesses: 90, totalCustomers: 25, totalProspects: 65, totalAnchors: 5, penetrationPercentage: 27.7, clusterStage: 4, latitude: 9.0300, longitude: 7.4880 },
];

export const mockClusterDetail: ClusterDetail = {
  id: 'banex',
  name: 'Banex Plaza Cluster',
  areaName: 'Wuse 2',
  cityName: 'Abuja',
  stateName: 'FCT',
  countryName: 'Nigeria',
  totalBusinesses: 120,
  verifiedBusinesses: 110,
  customersCount: 48,
  prospectsCount: 72,
  anchorBusinessesCount: 6,
  assignedAffiliatesCount: 3,
  penetrationPercentage: 40,
  discoveryProgress: 100,
  verificationProgress: 92,
  salesContactProgress: 60,
  partnershipsProgress: 20,
  overallCompletion: 54,
  currentStage: 6,
  nextRecommendedAction: 'Sign 1 major supermarket and 2 top restaurants to activate local customer-sharing ecosystem.',
  assignedAffiliates: [
    { id: 'aff-1', fullName: 'Emmanuel Nnamdi', businessesAssigned: 45, businessesVisited: 40, customersClosed: 20, performanceScore: 94 },
    { id: 'aff-2', fullName: 'Sarah Okafor', businessesAssigned: 40, businessesVisited: 35, customersClosed: 16, performanceScore: 88 },
    { id: 'aff-3', fullName: 'Chidi Bello', businessesAssigned: 35, businessesVisited: 28, customersClosed: 12, performanceScore: 81 },
  ],
  createdAt: '2026-05-10',
  updatedAt: '2026-07-28',
};

export const mockBusinesses: MappedBusiness[] = [
  {
    id: 'b-101',
    name: 'Grand Mega Supermarket',
    category: 'Supermarket',
    industry: 'Retail & Grocery',
    size: 'LARGE',
    status: 'CUSTOMER',
    isAnchor: true,
    anchorScore: 96,
    influenceScore: 98,
    isVerified: true,
    verifiedAt: '2026-06-02',
    verifiedBy: 'Emmanuel Nnamdi',
    ownerName: 'Chief Okonkwo',
    decisionMaker: 'David Okonkwo (General Manager)',
    phone: '+2348031234567',
    email: 'info@grandmega.com',
    website: 'https://grandmegamart.com',
    address: 'Block A, Ground Floor, Banex Plaza, Wuse 2, Abuja',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0765,
    longitude: 7.4898,
    dailyCustomers: 1200,
    monthlyCustomers: 36000,
    openingHours: '08:00 AM - 10:00 PM Daily',
    staffCount: 35,
    assignedAffiliateId: 'aff-1',
    assignedAffiliateName: 'Emmanuel Nnamdi',
    priority: 'HIGH',
    lastVisit: '2026-07-25',
    nextVisit: '2026-08-01',
    notes: 'Anchor supermarket driving high foot traffic. Key hub for ecosystem cross-promotions.',
    documents: [
      { id: 'd-1', title: 'Storefront Verification Photo', type: 'PHOTO', url: 'https://picsum.photos/400/300', uploadedAt: '2026-06-02' },
      { id: 'd-2', title: 'Vemtap Merchant Agreement', type: 'CONTRACT', url: '#', uploadedAt: '2026-06-15' },
    ],
    nearbyPartnerships: [
      { businessId: 'b-102', businessName: 'Banex Gourmet Restaurant', category: 'Restaurant', synergyScore: 92, description: 'Offer 10% meal voucher to grocery shoppers spending > N20,000' },
      { businessId: 'b-103', businessName: 'HealthPlus Pharmacy', category: 'Pharmacy', synergyScore: 88, description: 'Wellness rewards card integration' },
    ],
    tasks: [
      { id: 't-1', title: 'Deploy updated QR signage at checkout counter', status: 'COMPLETED', dueDate: '2026-07-20', assignedAffiliateName: 'Emmanuel Nnamdi' },
      { id: 't-2', title: 'Setup monthly co-marketing campaign with salon', status: 'PENDING', dueDate: '2026-08-05', assignedAffiliateName: 'Emmanuel Nnamdi' },
    ],
  },
  {
    id: 'b-102',
    name: 'Banex Gourmet Restaurant',
    category: 'Restaurant',
    industry: 'Food & Hospitality',
    size: 'MEDIUM',
    status: 'CUSTOMER',
    isAnchor: true,
    anchorScore: 89,
    influenceScore: 85,
    isVerified: true,
    verifiedAt: '2026-06-05',
    verifiedBy: 'Emmanuel Nnamdi',
    ownerName: 'Chef Amina Bello',
    decisionMaker: 'Amina Bello',
    phone: '+2348029876543',
    email: 'amina@banexgourmet.ng',
    address: 'Suite 12, First Floor, Banex Plaza, Abuja',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0768,
    longitude: 7.4902,
    dailyCustomers: 350,
    monthlyCustomers: 10500,
    openingHours: '10:00 AM - 11:00 PM',
    staffCount: 16,
    assignedAffiliateId: 'aff-1',
    assignedAffiliateName: 'Emmanuel Nnamdi',
    priority: 'HIGH',
    lastVisit: '2026-07-24',
    nextVisit: '2026-07-30',
    notes: 'Popular lunch and dinner spot in plaza.',
  },
  {
    id: 'b-103',
    name: 'HealthPlus Pharmacy',
    category: 'Pharmacy',
    industry: 'Healthcare',
    size: 'MEDIUM',
    status: 'MEETING',
    isAnchor: true,
    anchorScore: 85,
    influenceScore: 80,
    isVerified: true,
    verifiedAt: '2026-06-10',
    verifiedBy: 'Sarah Okafor',
    ownerName: 'Dr. Chike Nwosu',
    decisionMaker: 'Dr. Chike Nwosu',
    phone: '+2348035551234',
    address: 'Block B, Shop 4, Banex Plaza, Abuja',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0762,
    longitude: 7.4895,
    dailyCustomers: 280,
    monthlyCustomers: 8400,
    assignedAffiliateId: 'aff-2',
    assignedAffiliateName: 'Sarah Okafor',
    priority: 'HIGH',
    lastVisit: '2026-07-26',
    nextVisit: '2026-07-29',
    notes: 'High daily customer count. Demo scheduled for Thursday.',
  },
  {
    id: 'b-104',
    name: 'Elite Beauty Salon & Spa',
    category: 'Salon',
    industry: 'Beauty & Personal Care',
    size: 'SMALL',
    status: 'NEGOTIATING',
    isAnchor: false,
    anchorScore: 62,
    influenceScore: 70,
    isVerified: true,
    ownerName: 'Blessing Udoh',
    decisionMaker: 'Blessing Udoh',
    phone: '+2348071112233',
    address: 'Suite 8, Second Floor, Banex Plaza',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0770,
    longitude: 7.4905,
    dailyCustomers: 75,
    monthlyCustomers: 2250,
    assignedAffiliateId: 'aff-2',
    assignedAffiliateName: 'Sarah Okafor',
    priority: 'MEDIUM',
    lastVisit: '2026-07-22',
    nextVisit: '2026-07-31',
  },
  {
    id: 'b-105',
    name: 'Sparkle Express Laundry',
    category: 'Laundry',
    industry: 'Services',
    size: 'SMALL',
    status: 'PROSPECT',
    isAnchor: false,
    anchorScore: 45,
    influenceScore: 50,
    isVerified: false,
    ownerName: 'Tunde Bakare',
    decisionMaker: 'Tunde Bakare',
    phone: '+2348054443322',
    address: 'Basement Shop 2, Banex Plaza',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0761,
    longitude: 7.4910,
    dailyCustomers: 50,
    monthlyCustomers: 1500,
    assignedAffiliateId: 'aff-3',
    assignedAffiliateName: 'Chidi Bello',
    priority: 'LOW',
    lastVisit: '2026-07-15',
  },
  {
    id: 'b-106',
    name: 'Plaza Luxury Hotel & Suites',
    category: 'Hotel',
    industry: 'Hospitality',
    size: 'LARGE',
    status: 'PROSPECT',
    isAnchor: true,
    anchorScore: 94,
    influenceScore: 92,
    isVerified: true,
    ownerName: 'Alhaji Haruna Isa',
    decisionMaker: 'Mr. Jude (Operations Director)',
    phone: '+2348098887766',
    address: 'Plot 402, Adjacent Banex Plaza, Wuse 2',
    clusterId: 'banex',
    clusterName: 'Banex Plaza Cluster',
    latitude: 9.0780,
    longitude: 7.4890,
    dailyCustomers: 400,
    monthlyCustomers: 12000,
    assignedAffiliateId: 'aff-1',
    assignedAffiliateName: 'Emmanuel Nnamdi',
    priority: 'HIGH',
    notes: 'Major target anchor hotel. Needs C-level executive pitch.',
  },
];
