'use client';

import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import AdminLayout from '@/components/admin/AdminLayout';
import { useAdminUser, useUserHistory, useUserLocations, useUserReports, useUserTeam } from '@/services/useAdminHooks';
import { cn } from '@/lib/utils';
import type { AdminActivity, AdminLocationAssignment, AdminPerformanceReport, AdminTeamMember, User } from '@/types/api';
import { AlertCircle, ArrowLeft, BarChart3, Briefcase, Calendar, CheckCircle2, Clock, History, Loader2, MapPin, RefreshCw, Target, Users, Wallet } from 'lucide-react';
import { useState } from 'react';

type Tab = 'overview' | 'reports' | 'locations' | 'history' | 'team';

export default function AffiliateDetailPage() {
  const params = useParams<{ affiliateId: string }>();
  const router = useRouter();
  const affiliateId = params.affiliateId;
  const [activeTab, setActiveTab] = useState<Tab>('overview');
  const userQuery = useAdminUser(affiliateId);
  const reportsQuery = useUserReports(affiliateId);
  const locationsQuery = useUserLocations(affiliateId);
  const historyQuery = useUserHistory(affiliateId);
  const teamQuery = useUserTeam(affiliateId);

  const retry = () => { userQuery.refetch(); reportsQuery.refetch(); locationsQuery.refetch(); historyQuery.refetch(); teamQuery.refetch(); };
  const error = userQuery.error || reportsQuery.error || locationsQuery.error || historyQuery.error || teamQuery.error;
  if (userQuery.isLoading) return <AdminLayout><PageState loading message="Loading affiliate..." /></AdminLayout>;
  if (userQuery.error) return <AdminLayout><PageState message={userQuery.error instanceof Error ? userQuery.error.message : 'Unable to load affiliate.'} retry={retry} /></AdminLayout>;
  if (!userQuery.data) return <AdminLayout><PageState message="Affiliate not found." notFound /></AdminLayout>;
  const user = userQuery.data;
  const tabs: Tab[] = user.role === 'MANAGER' || user.role === 'SUPERVISOR' ? ['overview', 'reports', 'locations', 'history', 'team'] : ['overview', 'reports', 'locations', 'history'];
  const locations = locationsQuery.data?.marketMappingAssignments ?? [];
  const activities = historyQuery.data?.activities ?? [];
  const team = teamQuery.data?.teamMembers ?? [];

  return <AdminLayout><div className="max-w-6xl mx-auto space-y-6">
    <button onClick={() => router.push('/admin/affiliates')} className="flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 font-medium"><ArrowLeft className="w-4 h-4" />Back to Affiliates</button>
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="bg-gradient-to-r from-blue-600 to-indigo-700 h-32" /><div className="px-8 pb-8"><div className="flex items-end -mt-16 mb-6"><div className="w-28 h-28 rounded-[32px] bg-white p-1 shadow-xl"><div className="w-full h-full rounded-[28px] bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white text-4xl font-black">{user.fullName.charAt(0)}</div></div><div className="ml-5 pb-2"><div className="flex items-center gap-3 flex-wrap"><h1 className="text-2xl font-black text-slate-900">{user.fullName}</h1><span className="text-[10px] font-black px-2.5 py-1 rounded-lg uppercase tracking-widest bg-blue-100 text-blue-600">{user.role === 'MANAGER' ? 'Manager' : user.role === 'SUPERVISOR' ? 'Line Manager' : user.role}</span><span className={cn('text-[10px] font-bold px-2.5 py-1 rounded-full uppercase', user.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-600' : 'bg-red-100 text-red-600')}>{user.status}</span></div><p className="text-sm text-slate-500 mt-1 font-mono">{user.email}</p></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4"><Stat icon={<Briefcase />} label="Businesses" value={user._count?.businesses ?? 0} /><Stat icon={<Users />} label="Referrals" value={user._count?.referrals ?? 0} /><Stat icon={<Target />} label="Leads" value={user._count?.leads ?? 0} /><Stat icon={<Wallet />} label="Earnings" value={`₦${Number(user.totalEarnings || 0).toLocaleString()}`} /></div>
    </div></div>
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 flex flex-wrap gap-6"><Info icon={<Calendar />} label="Registered" value={new Date(user.createdAt).toLocaleDateString()} /><Info icon={<Clock />} label="Phone" value={user.phone || 'Not provided'} /><Info icon={<Target />} label="Daily Target" value={user.dailyLeadTarget == null ? 'Not set' : `${user.dailyLeadTarget} leads`} /></div>
    <div className="flex overflow-x-auto gap-1 bg-white rounded-2xl border border-slate-200 p-1.5 shadow-sm">{tabs.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={cn('px-4 py-2.5 rounded-xl text-xs font-bold capitalize whitespace-nowrap', activeTab === tab ? 'bg-blue-600 text-white' : 'text-slate-500 hover:bg-slate-100')}>{tab}</button>)}</div>
    {error && <InlineError message="Some affiliate data could not be loaded." onRetry={retry} />}
    {activeTab === 'overview' && <Overview report={reportsQuery.data} user={user} activities={activities} />}
    {activeTab === 'reports' && <Reports report={reportsQuery.data} loading={reportsQuery.isLoading} />}
    {activeTab === 'locations' && <Locations locations={locations} loading={locationsQuery.isLoading} />}
    {activeTab === 'history' && <HistoryPanel activities={activities} loading={historyQuery.isLoading} affiliateId={affiliateId} />}
    {activeTab === 'team' && <Team team={team} loading={teamQuery.isLoading} />}
  </div></AdminLayout>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: React.ReactNode }) { return <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100"><div className="flex items-center gap-2 text-blue-600 mb-1">{icon}<span className="text-[10px] font-bold uppercase tracking-widest">{label}</span></div><p className="text-2xl font-black text-slate-900">{value}</p></div>; }
function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3"><span className="text-slate-400">{icon}</span><div><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{label}</p><p className="text-sm font-bold text-slate-900">{value}</p></div></div>; }
function Overview({ report, user, activities }: { report: AdminPerformanceReport | null | undefined; user: User; activities: AdminActivity[] }) { return <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="font-black text-slate-900 mb-4 flex items-center gap-2"><Target className="w-5 h-5 text-violet-500" />Performance Targets</h2><div className="grid grid-cols-2 gap-3"><Metric label="Daily leads" value={user.dailyLeadTarget ?? 'Not set'} /><Metric label="Monthly conversions" value={user.monthlyConversionTarget ?? 'Not set'} /><Metric label="Reporting score" value={report ? `${report.reportingScore}%` : 'Unavailable'} /><Metric label="Attendance" value={report ? `${report.attendanceRate}%` : 'Unavailable'} /></div></section><section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="font-black text-slate-900 mb-4 flex items-center gap-2"><History className="w-5 h-5 text-amber-500" />Recent Activity</h2>{activities.length === 0 ? <Empty message="No activity recorded yet." /> : <div className="space-y-3">{activities.slice(0, 5).map(activity => <ActivityRow key={activity.id} activity={activity} />)}</div>}</section></div>; }
function Reports({ report, loading }: { report: AdminPerformanceReport | null | undefined; loading: boolean }) { if (loading) return <CardState loading />; if (!report) return <CardState message="No performance report available." />; return <section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="text-lg font-black text-slate-900 mb-5 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-blue-500" />{report.period} performance</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><Metric label="Total leads" value={report.totalLeads} /><Metric label="Conversions" value={report.totalConversions} /><Metric label="Earnings" value={`₦${report.totalEarnings.toLocaleString()}`} /><Metric label="Reporting score" value={`${report.reportingScore}%`} /></div><div className="mt-6 grid md:grid-cols-3 gap-4"><Metric label="Recent leads returned" value={report.leads.length} /><Metric label="Recent businesses returned" value={report.businesses.length} /><Metric label="Recent commissions returned" value={report.commissions.length} /></div></section>; }
function Locations({ locations, loading }: { locations: AdminLocationAssignment[]; loading: boolean }) { if (loading) return <CardState loading />; if (!locations.length) return <CardState message="No locations assigned." />; return <section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="text-lg font-black mb-5 flex items-center gap-2"><MapPin className="w-5 h-5 text-blue-500" />Assigned Locations</h2><div className="grid md:grid-cols-2 gap-4">{locations.map(location => <div key={location.id} className="p-5 bg-blue-50 rounded-2xl border border-blue-100"><h3 className="font-bold text-slate-900">{location.cluster.name}</h3><p className="text-xs text-slate-500 mt-1">{location.cluster.type} hierarchy</p><div className="mt-4 text-xs text-slate-600">Assigned {new Date(location.assignedAt).toLocaleDateString()}</div><Link href={`/admin/affiliates/${location.cluster.id}/history?locationId=${location.cluster.id}`} className="inline-block mt-4 text-xs font-bold text-blue-600">View activity</Link></div>)}</div></section>; }
function HistoryPanel({ activities, loading, affiliateId }: { activities: AdminActivity[]; loading: boolean; affiliateId: string }) { if (loading) return <CardState loading />; return <section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><div className="flex justify-between mb-5"><h2 className="text-lg font-black flex items-center gap-2"><History className="w-5 h-5 text-amber-500" />Activity History</h2><Link href={`/admin/affiliates/${affiliateId}/history`} className="text-xs font-bold text-blue-600">Full history</Link></div>{activities.length ? <div className="space-y-3">{activities.map(activity => <ActivityRow key={activity.id} activity={activity} />)}</div> : <Empty message="No activity recorded yet." />}</section>; }
function Team({ team, loading }: { team: AdminTeamMember[]; loading: boolean }) { if (loading) return <CardState loading />; if (!team.length) return <CardState message="No team members under this manager." />; return <section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="text-lg font-black mb-5 flex items-center gap-2"><Users className="w-5 h-5 text-blue-500" />Team Members</h2><div className="divide-y divide-slate-100">{team.map(member => <div key={member.id} className="py-4 flex justify-between"><div><p className="font-bold text-slate-900">{member.fullName}</p><p className="text-xs text-slate-500">{member.email}</p></div><span className="text-[10px] font-black text-blue-600">{member.role}</span></div>)}</div></section>; }
function ActivityRow({ activity }: { activity: AdminActivity }) { return <div className="flex gap-3 p-3 bg-slate-50 rounded-xl"><CheckCircle2 className="w-4 h-4 text-blue-600 mt-0.5" /><div><p className="text-sm font-bold text-slate-900">{activity.title}</p><p className="text-xs text-slate-600">{activity.description || activity.businessName || 'Activity recorded'}</p><p className="text-[10px] text-slate-400 mt-1">{new Date(activity.createdAt).toLocaleString()}</p></div></div>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="p-3 bg-slate-50 rounded-xl"><p className="text-[10px] font-bold text-slate-400 uppercase">{label}</p><p className="text-xl font-black text-slate-900 mt-1">{value}</p></div>; }
function Empty({ message }: { message: string }) { return <p className="text-sm text-slate-400 text-center py-8">{message}</p>; }
function CardState({ message, loading = false }: { message?: string; loading?: boolean }) { return <section className="bg-white rounded-3xl border border-slate-200 p-12 text-center">{loading ? <Loader2 className="w-7 h-7 animate-spin text-blue-600 mx-auto" /> : <Empty message={message || 'No data available.'} />}</section>; }
function InlineError({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="flex items-center justify-between gap-3 p-4 rounded-2xl bg-red-50 border border-red-100 text-sm text-red-700"><span className="flex items-center gap-2"><AlertCircle className="w-4 h-4" />{message}</span><button onClick={onRetry} className="flex items-center gap-1 font-bold"><RefreshCw className="w-3 h-3" />Retry</button></div>; }
function PageState({ message, loading = false, notFound = false, retry }: { message: string; loading?: boolean; notFound?: boolean; retry?: () => void }) { return <div className="text-center py-20"><div className="w-16 h-16 bg-slate-100 rounded-3xl flex items-center justify-center mx-auto mb-4">{loading ? <Loader2 className="w-8 h-8 animate-spin text-blue-600" /> : <AlertCircle className="w-8 h-8 text-red-400" />}</div><p className="text-lg font-bold text-slate-600">{message}</p>{retry && <button onClick={retry} className="mt-5 px-5 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-bold">Retry</button>}{notFound && <Link href="/admin/affiliates" className="block mt-5 text-sm text-blue-600">Back to affiliates</Link>}</div>; }
